services:
  app:
    build: .
    container_name: hrs-app
    ports:
      - "8080:8080"
    environment:
      JDBC_CONNECTION: jdbc:postgresql://postgres:5432/hrs
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: hrs
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hrs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=tam070397@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 2000:80

volumes:
  postgres_data:
