spring:
  datasource:
    url: ${JDBC_CONNECTION:jdbc:postgresql://localhost:5432/hrs}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    hibernate:
      show-sql: true
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG